export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const GET_USER_TRANSACTIONS = 'GET_USER_TRANSACTIONS';
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
