export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const GET_USER_TRANSACTIONS = 'GET_USER_TRANSACTIONS';

